### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by RedHatter** [tableflip/guvnor#105]
I'm attempting to switch from pm2 to guvnor but can't get it to install. It looks like something is wrong with my permissions.

    $ npm install -g guvnor --unsafe-perm
    npm ERR! code 128
    npm ERR! Command failed: /usr/bin/git clone -q git://github.com/achingbrain/stylizer.git /root/.npm/_cacache/tmp/git-clone-90db64cb
    npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-90db64cb': Permission denied
    npm ERR!

My node was installed using the following commands.

    curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
    apt-get install -y nodejs

**Comment by RedHatter** [comment]
I was able to get further in the install process by running with `sudo`. Which is really weird as I was already logged in as root.

I'm having more issues though. The build process fails now. For brevity I extracted the errors from the output.

    node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v59-linux-x64.tar.gz
    node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@9.11.2 (node-v59 ABI, glibc) (falling back to source compile with node-gyp)
       ^
    ../src/debug.cc:38:27: error: no matching function for call to ‘v8::Debug::Call(v8::Local<v8::Function>&)’
             v8::Debug::Call(fn);

    ../src/debug.cc:46:61: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
             Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate();

    ../src/debug.cc:61:67: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
             Local<Context> debug_context = v8::Debug::GetDebugContext();

    ../src/debug.cc:65:11: error: ‘GetMirror’ is not a member of ‘v8::Debug’
               v8::Debug::GetMirror(info.GetIsolate()->GetCurrentContext(), info[0]);
               ^
    ../src/debug.cc:66:38: warning: ‘static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)’ is deprecated: Use v8-inspector [-Wdeprecated-declarations]
               debug_context = v8::Debug::GetDebugContext();
                                          ^
    ../src/debug.cc:66:54: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
               debug_context = v8::Debug::GetDebugContext();
                                                          ^
    debug.target.mk:98: recipe for target 'Release/obj.target/debug/src/debug.o' failed
    make: *** [Release/obj.target/debug/src/debug.o] Error 1
    make: Leaving directory '/usr/lib/node_modules/guvnor/node_modules/v8-debug/build'
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
    gyp ERR! System Linux 4.4.0-131-generic
    gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/guvnor/node_modules/v8-debug/build/debug/v0.7.7/node-v59-linux-x64/debug.node" "--module_name=debug" "--module_path=/usr/lib/node_modules/guvnor/node_modules/v8-debug/build/debug/v0.7.7/node-v59-linux-x64"
    gyp ERR! cwd /usr/lib/node_modules/guvnor/node_modules/v8-debug
    gyp ERR! node -v v9.11.2
    gyp ERR! node-gyp -v v3.6.2
    gyp ERR! not ok
    node-pre-gyp ERR! build error
    node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/guvnor/node_modules/v8-debug/build/debug/v0.7.7/node-v59-linux-x64/debug.node --module_name=debug --module_path=/usr/lib/node_modules/guvnor/node_modules/v8-debug/build/debug/v0.7.7/node-v59-linux-x64' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/guvnor/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:936:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
    node-pre-gyp ERR! System Linux 4.4.0-131-generic
    node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/guvnor/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd /usr/lib/node_modules/guvnor/node_modules/v8-debug
    node-pre-gyp ERR! node -v v9.11.2
    node-pre-gyp ERR! node-pre-gyp -v v0.6.39
    node-pre-gyp ERR! not ok

**Comment by elilambnz** [comment]
@RedHatter please note that guvnor hasn't been updated since 8 Jan 2016, so we can assume it isn't up to date with the latest version of Node, you're trying to install this with `v9.11.2`.

If you would like to use this project, you need to downgrade your version of Node. Consider using [nvm](https://github.com/creationix/nvm) to manage your Node versions. Version 5 or earlier should do the trick.

If you absolutely need to use the latest and greatest version of Node, [pm2-web](https://github.com/achingbrain/pm2-web) should work on the latest version. It has the same main author as this package.

**Comment by Remi-Tuy** [comment]
@elilambnz pm2-web has not been maintained since 2015 :/

**Comment by elilambnz** [comment]
@Remi-Tuy you’re right, but it does a pretty good job of monitoring node processes on a single machine. It doesn’t have as many features as guvnor though.
