### ISSUE TITLE
Uncaught exception group id does not exist

### ISSUE THREAD

**Issue by alanshaw** [tableflip/guvnor#22]
```
# bs list -v
debug: Loaded config from 0=/etc/boss/bossrc, 1=/usr/local/lib/node_modules/process-boss/bossrc
warn: Boss has been configured to start with the group 'boss' but that group does not exist
prompt: create group 'boss' [Y/n]:  (Y) Y
debug: Creating group boss
debug: /usr/sbin/groupadd boss
Usage: groupadd [options] GROUP

Options:
  -f, --force                   exit successfully if the group already exists,
                                and cancel -g if the GID is already used
  -g, --gid GID                 use GID for the new group
  -h, --help                    display this help message and exit
  -K, --key KEY=VALUE           override /etc/login.defs defaults
  -o, --non-unique              allow to create groups with duplicate
                                (non-unique) GID
  -p, --password PASSWORD       use this encrypted password for the new group
  -r, --system                  create a system account

debug: Will attempt to connect or start daemon
debug: Connecting to daemon on /var/run/boss/user.socket
debug: Socket file did not exist - the daemon is probably not running
debug: Daemon was not running so will start it
debug: Starting daemon
error: Uncaught exception group id does not exist
error: Error: group id does not exist
    at LocalDaemonStarter._startDaemonWithDebugPort (/usr/local/lib/node_modules/process-boss/node_modules/boss-local/lib/LocalDaemonStarter.js:52:22)
    at LocalDaemonStarter.start (/usr/local/lib/node_modules/process-boss/node_modules/boss-local/lib/LocalDaemonStarter.js:33:10)
    at null.<anonymous> (/usr/local/lib/node_modules/process-boss/node_modules/boss-local/lib/LocalDaemon.js:93:32)
    at null.<anonymous> (/usr/local/lib/node_modules/process-boss/node_modules/boss-local/lib/LocalDaemonConnection.js:117:14)
    at D.emit (events.js:117:20)
    at Socket.<anonymous> (/usr/local/lib/node_modules/process-boss/node_modules/boss-local/node_modules/dnode/index.js:65:14)
    at Socket.emit (events.js:117:20)
    at net.js:441:14
    at process._tickCallback (node.js:442:13)
    ---- async ----
    at fireErrorCallbacks (net.js:440:15)
    at Socket._destroy (net.js:476:3)
    at Object.afterConnect [as oncomplete] (net.js:896:10)
    ---- async ----
    at maybeReadMore (_stream_readable.js:440:13)
    at readableAddChunk (_stream_readable.js:168:7)
    at ReadStream.Readable.push (_stream_readable.js:128:10)
    at TTY.onread (net.js:529:21)
    ---- async ----
    at maybeReadMore (_stream_readable.js:440:13)
    at readableAddChunk (_stream_readable.js:168:7)
    at ReadStream.Readable.push (_stream_readable.js:128:10)
    at TTY.onread (net.js:529:21)
    ---- async ----
    at onwrite (_stream_writable.js:266:15)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at WriteStream.Socket._write (net.js:654:5)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at WriteStream.Writable.write (_stream_writable.js:183:11)
    at WriteStream.Socket.write (net.js:616:40)
    at MuteStream.ondata (stream.js:51:26)
    at MuteStream.emit (events.js:95:17)
    at MuteStream.write (/usr/local/lib/node_modules/process-boss/node_modules/prompt/node_modules/read/node_modules/mute-stream/mute.js:116:8)
    at Object.cursorTo (readline.js:1113:12)
    at Interface._refreshLine (readline.js:255:11)
    at Interface.prompt (readline.js:175:10)
    at read (/usr/local/lib/node_modules/process-boss/node_modules/prompt/node_modules/read/lib/read.js:51:6)
    at EventEmitter.prompt.getInput (/usr/local/lib/node_modules/process-boss/node_modules/prompt/lib/prompt.js:502:3)
    at get (/usr/local/lib/node_modules/process-boss/node_modules/prompt/lib/prompt.js:321:12)
    at /usr/local/lib/node_modules/process-boss/node_modules/prompt/lib/prompt.js:280:7
    at iterate (/usr/local/lib/node_modules/process-boss/node_modules/prompt/node_modules/utile/node_modules/async/lib/async.js:134:13)
    at Object.async.eachSeries (/usr/local/lib/node_modules/process-boss/node_modules/prompt/node_modules/utile/node_modules/async/lib/async.js:150:9)
    at iterate (/usr/local/lib/node_modules/process-boss/node_modules/prompt/lib/prompt.js:279:11)
    at EventEmitter.prompt.get (/usr/local/lib/node_modules/process-boss/node_modules/prompt/lib/prompt.js:320:3)
    at CLI._checkBossGroup (/usr/local/lib/node_modules/process-boss/lib/CLI.js:292:20)
    at /usr/local/lib/node_modules/process-boss/node_modules/async/lib/async.js:610:21
    at /usr/local/lib/node_modules/process-boss/node_modules/async/lib/async.js:249:17
    at iterate (/usr/local/lib/node_modules/process-boss/node_modules/async/lib/async.js:149:13)
    at /usr/local/lib/node_modules/process-boss/node_modules/async/lib/async.js:160:25
    at /usr/local/lib/node_modules/process-boss/node_modules/async/lib/async.js:251:21
    at /usr/local/lib/node_modules/process-boss/node_modules/async/lib/async.js:615:34
    at CLI._checkBossUser (/usr/local/lib/node_modules/process-boss/lib/CLI.js:232:12)
    at /usr/local/lib/node_modules/process-boss/node_modules/async/lib/async.js:610:21
    at /usr/local/lib/node_modules/process-boss/node_modules/async/lib/async.js:249:17
    at iterate (/usr/local/lib/node_modules/process-boss/node_modules/async/lib/async.js:149:13)
    at async.eachSeries (/usr/local/lib/node_modules/process-boss/node_modules/async/lib/async.js:165:9)
    at _asyncMap (/usr/local/lib/node_modules/process-boss/node_modules/async/lib/async.js:248:13)
    at Object.mapSeries (/usr/local/lib/node_modules/process-boss/node_modules/async/lib/async.js:231:23)
    at Object.async.series (/usr/local/lib/node_modules/process-boss/node_modules/async/lib/async.js:608:19)
    at CLI.afterPropertiesSet (/usr/local/lib/node_modules/process-boss/lib/CLI.js:32:9)
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:929:3
    ---- async ----
    at Container.create (/usr/local/lib/node_modules/process-boss/node_modules/wantsit/lib/Container.js:116:13)
    at Container.createAndRegister (/usr/local/lib/node_modules/process-boss/node_modules/wantsit/lib/Container.js:88:29)
    at Object.<anonymous> (/usr/local/lib/node_modules/process-boss/index.js:40:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/process-boss/bin/bs:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by PavelVanecekGIC** [comment]
I'm still seeing this:

    $ guv list

    /usr/local/lib/node_modules/guvnor/lib/cli/index.js:28
    container.register('group', require('posix').getgrnam(process.getgid()))
                                                 ^
    Error: group id does not exist
        at Object.<anonymous> (/usr/local/lib/node_modules/guvnor/lib/cli/index.js:28:46)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/usr/local/lib/node_modules/guvnor/bin/guv:3:1)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)

OSX 10.10
node.js 0.10.36

**Comment by bluejamesbond** [comment]
```bash
$ guv list

/Users/meh/.nvm/versions/node/v5.0.0/lib/node_modules/guvnor/lib/cli/index.js:30
  container.register('group', require('posix').getgrnam(process.getgid()))
                                               ^

Error: group id does not exist
    at Error (native)
    at module.exports (/Users/meh/.nvm/versions/node/v5.0.0/lib/node_modules/guvnor/lib/cli/index.js:30:48)
    at Object.<anonymous> (/Users/meh/.nvm/versions/node/v5.0.0/lib/node_modules/guvnor/bin/guv:3:35)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

**Comment by achingbrain** [comment]
Is there a group named `guvnor` in `/etc/groups` on your system?
