### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by crunchprank** [tableflip/guvnor#83]
**OS and Software Versions**
```
[root@local ~]# cat /etc/*-release
CentOS release 6.7 (Final)
[root@local ~]# npm -v
3.5.2
[root@local ~]# node -v
v4.2.3
```
**Issue**
I'm running into an issue when attempting to install Guvnor via

```
npm install -g guvnor --unsafe-perm
```

It looks to me that it is indicating a compatibility issue with Guvnor and the versions of node / node-gyp. Am I running too new of a version to properly install Guvnor?

**Error Log**
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v4.2.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-504.30.3.el6.x86_64
gyp ERR! command "/root/.nvm/versions/node/v4.2.3/bin/node" "/root/.nvm/versions/node/v4.2.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.nvm/versions/node/v4.2.3/lib/node_modules/guvnor/node_modules/heapdump
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
/root/.nvm/versions/node/v4.2.3/lib
└── (empty)

npm WARN optional Skipping failed optional dependency /guvnor/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
npm ERR! Linux 2.6.32-504.30.3.el6.x86_64
npm ERR! argv "/root/.nvm/versions/node/v4.2.3/bin/node" "/root/.nvm/versions/node/v4.2.3/bin/npm" "install" "-g" "guvnor" "--unsafe-perm"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! heapdump@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs heapdump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.
```

**npm-debug.log**
```
68137 warn optional Skipping failed optional dependency /guvnor/chokidar/fsevents:
68138 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.6
68139 verbose stack Error: heapdump@0.3.7 install: `node-gyp rebuild`
68139 verbose stack Exit status 1
68139 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v4.2.3/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
68139 verbose stack     at emitTwo (events.js:87:13)
68139 verbose stack     at EventEmitter.emit (events.js:172:7)
68139 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v4.2.3/lib/node_modules/npm/lib/utils/spawn.js:24:14)
68139 verbose stack     at emitTwo (events.js:87:13)
68139 verbose stack     at ChildProcess.emit (events.js:172:7)
68139 verbose stack     at maybeClose (internal/child_process.js:818:16)   
68139 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
68140 verbose pkgid heapdump@0.3.7
68141 verbose cwd /root
68142 error Linux 2.6.32-504.30.3.el6.x86_64
68143 error argv "/root/.nvm/versions/node/v4.2.3/bin/node" "/root/.nvm/versions/node/v4.2.3/bin/npm" "install" "-g" "guvnor" "--unsafe-perm"
68144 error node v4.2.3
68145 error npm  v3.5.2
68146 error code ELIFECYCLE
68147 error heapdump@0.3.7 install: `node-gyp rebuild`
68147 error Exit status 1
68148 error Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
68148 error Make sure you have the latest version of node.js and npm installed.
68148 error If you do, this is most likely a problem with the heapdump package,
68148 error not with npm itself.
68148 error Tell the author that this fails on your system:
68148 error     node-gyp rebuild
68148 error You can get information on how to open an issue for this project with:
68148 error     npm bugs heapdump
68148 error Or if that isn't available, you can get their info via:
68148 error     npm owner ls heapdump
68148 error There is likely additional logging output above.
68149 verbose exit [ 1, true ]
```

**Comment by achingbrain** [comment]
I think your version of GCC needs to be updated - see bnoordhuis/node-heapdump#72

**Comment by crunchprank** [comment]
You were exactly right. I was running 4.4.7, so I built gcc 4.8.2 from source, installed it, and then was able to successfully install guvnor. Thank ya, bud.

**Comment by achingbrain** [comment]
No worries, happy to help.
