### ISSUE TITLE
Seems a little bit strange, why 

### ISSUE THREAD

**Issue by mike442144** [tableflip/guvnor#90]
It seems strange when I run the command as following:

root@iZ28sy91bq6Z:~# guv list
No running processes
root@iZ28sy91bq6Z:~# guv list
error: Daemon was not running
root@iZ28sy91bq6Z:~# guv list
No running processes
root@iZ28sy91bq6Z:~# guv list
error: Daemon was not running
root@iZ28sy91bq6Z:~# guv list
error: Daemon was not running
root@iZ28sy91bq6Z:~# guv list
No running processes
root@iZ28sy91bq6Z:~# guv list
error: Daemon was not running
root@iZ28sy91bq6Z:~# guv list
error: Daemon was not running
root@iZ28sy91bq6Z:~# guv list
error: Daemon was not running
root@iZ28sy91bq6Z:~# guv list
No running processes

why?

**Comment by achingbrain** [comment]
Is anything getting added to the error logs under `/var/log/guvnor` ?

**Comment by mike442144** [comment]
@achingbrain yep, like this, 

`uncaughtException: listen EADDRINUSE`

why?

**Comment by achingbrain** [comment]
Something may be listening on port 57483 or 57484.  Can you try running `lsof -i :57483` when you see `EADDRINUSE` appear?

Also, can you post the whole error log?

**Comment by mike442144** [comment]
@achingbrain Sure, 

> {"level":"error","message":"Could not create connection to remote process Error: connect ECONNRESET\n    at exports._errnoException (util.js:746:11)\n    at PipeConnectWrap.afterConnect [as oncomplete](net.js:1010:19)","timestamp":"2015-11-24T03:26:26.342Z"}
> {"level":"error","message":"Could not create connection to remote process Error: read ECONNRESET\n    at exports._errnoException (util.js:746:11)\n    at Pipe.onread (net.js:559:26)","timestamp":"2015-11-24T03:26:28.177Z"}
> {"level":"error","message":"Could not create connection to remote process Error: read ECONNRESET\n    at exports._errnoException (util.js:746:11)\n    at Pipe.onread (net.js:559:26)","timestamp":"2015-11-24T03:26:30.029Z"}
> {"level":"error","message":"Could not create connection to remote process Error: connect ECONNREFUSED\n    at exports._errnoException (util.js:746:11)\n    at PipeConnectWrap.afterConnect [as oncomplete](net.js:1010:19)","timestamp":"2015-11-24T03:26:31.886Z"}
> {"level":"error","message":"Could not create connection to remote process Error: read ECONNRESET\n    at exports._errnoException (util.js:746:11)\n    at Pipe.onread (net.js:559:26)","timestamp":"2015-11-24T03:26:33.694Z"}
> {"date":"Wed Feb 03 2016 17:52:38 GMT+0800 (CST)","process":{"pid":7594,"uid":0,"gid":1000,"cwd":"/run/guvnor","execPath":"/usr/bin/nodejs","version":"v0.12.4","argv":["/usr/bin/nodejs","/usr/lib/node_modules/guvnor/lib/daemon/index.js"],"memoryUsage":{"rss":31490048,"heapTotal":30566144,"heapUsed":12709848}},"os":{"loadavg":[1.93408203125,1.42236328125,1.3828125],"uptime":8624548},"trace":[{"column":11,"file":"util.js","function":"exports._errnoException","line":746,"method":"_errnoException","native":false},{"column":14,"file":"net.js","function":"Server._listen2","line":1156,"method":"_listen2","native":false},{"column":10,"file":"net.js","function":"listen","line":1182,"method":null,"native":false},{"column":9,"file":"net.js","function":null,"line":1280,"method":null,"native":false},{"column":18,"file":"dns.js","function":null,"line":85,"method":null,"native":false},{"column":11,"file":"node.js","function":"process._tickCallback","line":355,"method":"_tickCallback","native":false}],"stack":["Error: listen EADDRINUSE","    at exports._errnoException (util.js:746:11)","    at Server._listen2 (net.js:1156:14)","    at listen (net.js:1182:10)","    at net.js:1280:9","    at dns.js:85:18","    at process._tickCallback (node.js:355:11)"],"level":"error","message":"uncaughtException: listen EADDRINUSE","timestamp":"2016-02-03T09:52:38.992Z"}
> {"date":"Wed Feb 03 2016 17:52:46 GMT+0800 (CST)","process":{"pid":7642,"uid":0,"gid":1000,"cwd":"/run/guvnor","execPath":"/usr/bin/nodejs","version":"v0.12.4","argv":["/usr/bin/nodejs","/usr/lib/node_modules/guvnor/lib/daemon/index.js"],"memoryUsage":{"rss":31449088,"heapTotal":30566144,"heapUsed":12679328}},"os":{"loadavg":[1.716796875,1.39208984375,1.37353515625],"uptime":8624555},"trace":[{"column":11,"file":"util.js","function":"exports._errnoException","line":746,"method":"_errnoException","native":false},{"column":14,"file":"net.js","function":"Server._listen2","line":1156,"method":"_listen2","native":false},{"column":10,"file":"net.js","function":"listen","line":1182,"method":null,"native":false},{"column":9,"file":"net.js","function":null,"line":1280,"method":null,"native":false},{"column":18,"file":"dns.js","function":null,"line":85,"method":null,"native":false},{"column":11,"file":"node.js","function":"process._tickCallback","line":355,"method":"_tickCallback","native":false}],"stack":["Error: listen EADDRINUSE","    at exports._errnoException (util.js:746:11)","    at Server._listen2 (net.js:1156:14)","    at listen (net.js:1182:10)","    at net.js:1280:9","    at dns.js:85:18","    at process._tickCallback (node.js:355:11)"],"level":"error","message":"uncaughtException: listen EADDRINUSE","timestamp":"2016-02-03T09:52:46.311Z"}
> {"date":"Wed Feb 03 2016 17:52:48 GMT+0800 (CST)","process":{"pid":7664,"uid":0,"gid":1000,"cwd":"/run/guvnor","execPath":"/usr/bin/nodejs","version":"v0.12.4","argv":["/usr/bin/nodejs","/usr/lib/node_modules/guvnor/lib/daemon/index.js"],"memoryUsage":{"rss":31576064,"heapTotal":30566144,"heapUsed":12717592}},"os":{"loadavg":[1.716796875,1.39208984375,1.37353515625],"uptime":8624558},"trace":[{"column":11,"file":"util.js","function":"exports._errnoException","line":746,"method":"_errnoException","native":false},{"column":14,"file":"net.js","function":"Server._listen2","line":1156,"method":"_listen2","native":false},{"column":10,"file":"net.js","function":"listen","line":1182,"method":null,"native":false},{"column":9,"file":"net.js","function":null,"line":1280,"method":null,"native":false},{"column":18,"file":"dns.js","function":null,"line":85,"method":null,"native":false},{"column":11,"file":"node.js","function":"process._tickCallback","line":355,"method":"_tickCallback","native":false}],"stack":["Error: listen EADDRINUSE","    at exports._errnoException (util.js:746:11)","    at Server._listen2 (net.js:1156:14)","    at listen (net.js:1182:10)","    at net.js:1280:9","    at dns.js:85:18","    at process._tickCallback (node.js:355:11)"],"level":"error","message":"uncaughtException: listen EADDRINUSE","timestamp":"2016-02-03T09:52:48.567Z"}
> {"date":"Wed Feb 03 2016 17:52:53 GMT+0800 (CST)","process":{"pid":7712,"uid":0,"gid":1000,"cwd":"/run/guvnor","execPath":"/usr/bin/nodejs","version":"v0.12.4","argv":["/usr/bin/nodejs","/usr/lib/node_modules/guvnor/lib/daemon/index.js"],"memoryUsage":{"rss":31416320,"heapTotal":30566144,"heapUsed":12636312}},"os":{"loadavg":[1.7392578125,1.40234375,1.376953125],"uptime":8624563},"trace":[{"column":11,"file":"util.js","function":"exports._errnoException","line":746,"method":"_errnoException","native":false},{"column":14,"file":"net.js","function":"Server._listen2","line":1156,"method":"_listen2","native":false},{"column":10,"file":"net.js","function":"listen","line":1182,"method":null,"native":false},{"column":9,"file":"net.js","function":null,"line":1280,"method":null,"native":false},{"column":18,"file":"dns.js","function":null,"line":85,"method":null,"native":false},{"column":11,"file":"node.js","function":"process._tickCallback","line":355,"method":"_tickCallback","native":false}],"stack":["Error: listen EADDRINUSE","    at exports._errnoException (util.js:746:11)","    at Server._listen2 (net.js:1156:14)","    at listen (net.js:1182:10)","    at net.js:1280:9","    at dns.js:85:18","    at process._tickCallback (node.js:355:11)"],"level":"error","message":"uncaughtException: listen EADDRINUSE","timestamp":"2016-02-03T09:52:53.895Z"}
> {"date":"Wed Feb 03 2016 17:52:55 GMT+0800 (CST)","process":{"pid":7734,"uid":0,"gid":1000,"cwd":"/run/guvnor","execPath":"/usr/bin/nodejs","version":"v0.12.4","argv":["/usr/bin/nodejs","/usr/lib/node_modules/guvnor/lib/daemon/index.js"],"memoryUsage":{"rss":31551488,"heapTotal":30566144,"heapUsed":12590672}},"os":{"loadavg":[1.84033203125,1.4287109375,1.3857421875],"uptime":8624565},"trace":[{"column":11,"file":"util.js","function":"exports._errnoException","line":746,"method":"_errnoException","native":false},{"column":14,"file":"net.js","function":"Server._listen2","line":1156,"method":"_listen2","native":false},{"column":10,"file":"net.js","function":"listen","line":1182,"method":null,"native":false},{"column":9,"file":"net.js","function":null,"line":1280,"method":null,"native":false},{"column":18,"file":"dns.js","function":null,"line":85,"method":null,"native":false},{"column":11,"file":"node.js","function":"process._tickCallback","line":355,"method":"_tickCallback","native":false}],"stack":["Error: listen EADDRINUSE","    at exports._errnoException (util.js:746:11)","    at Server._listen2 (net.js:1156:14)","    at listen (net.js:1182:10)","    at net.js:1280:9","    at dns.js:85:18","    at process._tickCallback (node.js:355:11)"],"level":"error","message":"uncaughtException: listen EADDRINUSE","timestamp":"2016-02-03T09:52:55.756Z"}
> {"date":"Wed Feb 03 2016 17:52:57 GMT+0800 (CST)","process":{"pid":7756,"uid":0,"gid":1000,"cwd":"/run/guvnor","execPath":"/usr/bin/nodejs","version":"v0.12.4","argv":["/usr/bin/nodejs","/usr/lib/node_modules/guvnor/lib/daemon/index.js"],"memoryUsage":{"rss":31457280,"heapTotal":30566144,"heapUsed":12662104}},"os":{"loadavg":[1.84033203125,1.4287109375,1.3857421875],"uptime":8624567},"trace":[{"column":11,"file":"util.js","function":"exports._errnoException","line":746,"method":"_errnoException","native":false},{"column":14,"file":"net.js","function":"Server._listen2","line":1156,"method":"_listen2","native":false},{"column":10,"file":"net.js","function":"listen","line":1182,"method":null,"native":false},{"column":9,"file":"net.js","function":null,"line":1280,"method":null,"native":false},{"column":18,"file":"dns.js","function":null,"line":85,"method":null,"native":false},{"column":11,"file":"node.js","function":"process._tickCallback","line":355,"method":"_tickCallback","native":false}],"stack":["Error: listen EADDRINUSE","    at exports._errnoException (util.js:746:11)","    at Server._listen2 (net.js:1156:14)","    at listen (net.js:1182:10)","    at net.js:1280:9","    at dns.js:85:18","    at process._tickCallback (node.js:355:11)"],"level":"error","message":"uncaughtException: listen EADDRINUSE","timestamp":"2016-02-03T09:52:57.767Z"}

all above.

when I got error like Daeomon was not running, lsof -i :57483 output like:

`guvnor  7534 root   12u  IPv4 183206972      0t0  TCP *:57483 (LISTEN)`

**Comment by achingbrain** [comment]
Could you run `guv list -v` a few times and paste the output?  The `-v` flag will enable verbose output.

**Comment by mike442144** [comment]
@achingbrain 
sure, when it threw error, I got this:
debug: Loaded config from 0=/usr/lib/node_modules/guvnor/guvnor
debug: ApplicationContext Component with name config is being overridden
debug: ApplicationContext Component with name logger is being overridden
debug: Connecting to daemon on /var/run/guvnor/user.socket
debug: Socket file did not exist - the daemon is probably not running
debug: Daemon was not running so will start it
debug: Starting daemon
debug: Daemon requested config
debug: Daemon process online
debug: Daemon started
debug: Connecting to daemon on /var/run/guvnor/user.socket
debug: Disconnected from Daemon process
debug: Socket file did not exist - the daemon is probably not running
error: Uncaught exception Daemon was not running
error: Error: Daemon was not running
    at null.<anonymous> (/usr/lib/node_modules/guvnor/lib/local/LocalDaemonConnection.js:151:15)
    at D.emit (events.js:129:20)
    at Socket.<anonymous> (/usr/lib/node_modules/guvnor/node_modules/boss-dnode/index.js:71:14)
    at Socket.emit (events.js:129:20)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)

**Comment by mike442144** [comment]
@achingbrain Any update?

**Comment by achingbrain** [comment]
Does the folder `/var/run/guvnor` exist?  From the log files the current working directory of the process is `/run/guvnor` which looks wrong - did you change the default run directory or similar?

**Comment by mike442144** [comment]
@achingbrain Yes, the `/var/run/guvnor` exists. 

```
root@iZ28sy91bq6Z:~# ls /var/run/guvnor
processes  user.socket
```

**Comment by mike442144** [comment]
@achingbrain Sorry, any updates?
